logo: # add logo name
title: Xtapo - Sexy Girl Photos
description: > # this means to ignore newlines until "baseurl:"
  Sexy Girl, Cute Girl, Beautiful Girl: Photos
permalink: ':title/'
#baseurl: "/bef" # the subpath of your site, e.g. /blog
url: "https://photos.xtapo.com" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: # add banner title
banner-desc: # add banner description

# Author settings
author-pic: face.jpg # your photo
author-name: # your name
about-author: # about author
email: info@xtapo.com # your email
# phone: (496)-169-6557 # your pnone number
website: https://xtapo.com # you website

# Social link
google_url:    # add url link
twitter_url:   # add url link
instagram_url: # add url link
pinterest_url: # add url link
dribbble_url:  # add url link
facebook_url:  https://facebook.com/xtapocom

# Disqus
discus_identifier: photoxtapo # add your discus identifier

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics: UA-122951322-1

# Paginate
paginate: 21
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
